### ISSUE TITLE
Connection closed by peer

### ISSUE THREAD

**Issue by jufei** [Swind/pure-python-adb#13]
hi:
   The pure python adb library is very useful for me. But I met a strange issue:

I have a PC (named PCA), the PC connects 2 Android devices and the PC uses windows 7.

I installed the pure python adb library on the PC and use it to execute some adb shell command on addroid devices. It works fine.

I have another PC (named PCB), it uses centos 7 and also have installed the pure python adb library. For some reason, I wish to access the andirod devices of PCA from PCB.  I know the adb only listen on 127.0.0.1 5037 of PCA, and I could not connect to PCA with pure-python-adb; 

So I installed a softeware on PCA that will do port forward, for example: the PCA's ip address is 10.69.67.139, so I set in the port forword software, use it to forward any ip packet to 10.69.67.130:5036 to 127.0.0.1:5037,  this time, I can use pure-python-adb to connect to 19.69.67.139:5036. It also works.

My issue is: sometimes the pure-python-adb will broken for connection reset by peer. I means sometimes means: sometimes it is ok, but sometimes it fails; even I execute the same shell command.

the error log is something like this:

01-02-2019:09:15:43,231 DEBUG    [connection.py:24] Connect to adb server - 10.69.67.139:5036
2019-02-01 09:15:43 [DEBUG] Connect to adb server - 10.69.67.139:5036
01-02-2019:09:15:43,232 DEBUG    [connection.py:75] 000Chost:devices
2019-02-01 09:15:43 [DEBUG] 000Chost:devices
01-02-2019:09:15:43,234 DEBUG    [connection.py:47] Connection closed...
2019-02-01 09:15:43 [DEBUG] Connection closed...
2019-02-01 09:15:43 [ INFO] shell: ifconfig
01-02-2019:09:15:43,235 DEBUG    [connection.py:24] Connect to adb server - 10.69.67.139:5036
2019-02-01 09:15:43 [DEBUG] Connect to adb server - 10.69.67.139:5036
01-02-2019:09:15:43,235 DEBUG    [connection.py:24] Connect to adb server - 10.69.67.139:5036
2019-02-01 09:15:43 [DEBUG] Connect to adb server - 10.69.67.139:5036
01-02-2019:09:15:43,236 DEBUG    [connection.py:75] 001Fhost:transport:5LM0216922003133
2019-02-01 09:15:43 [DEBUG] 001Fhost:transport:5LM0216922003133
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "adb_proxy.py", line 140, in run
    self.deal_message(message, address)
  File "adb_proxy.py", line 128, in deal_message
    response = self.tc.dealwith_direct_operation(data)
  File "adb_proxy.py", line 83, in dealwith_direct_operation
    return self._run_shell_command(device, command)
  File "adb_proxy.py", line 67, in _run_shell_command
    device.shell('{}'.format(command)))
  File "/usr/lib/python2.7/site-packages/adb/command/transport/__init__.py", line 20, in shell
    conn = self.create_connection(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/adb/device.py", line 45, in create_connection
    self.transport(conn)
  File "/usr/lib/python2.7/site-packages/adb/command/transport/__init__.py", line 15, in transport
    connection.send(cmd)
  File "/usr/lib/python2.7/site-packages/adb/connection.py", line 77, in send
    return self._check_status()
  File "/usr/lib/python2.7/site-packages/adb/connection.py", line 80, in _check_status
    recv = self._recv(4).decode('utf-8')
  File "/usr/lib/python2.7/site-packages/adb/connection.py", line 56, in _recv
    return self.socket.recv(length)
error: [Errno 104] Connection reset by peer

Thanks in advance.

**Comment by jufei** [comment]
I think this issue maybe caused by a bug.

In device.py line 42:
conn.connect()

But in fact, in self.client.create_connection(timeout=timeout), the connection has ben connected;
so it will connect twice!

I comment this line and it works well.

**Comment by Swind** [comment]
Hi @jufei 

sorry for late reply
Thanks ! you are right.
I will fix this.
