### ISSUE TITLE
adb.devices() returns ERROR: 'Andr' oid Console: type 'help' for...

### ISSUE THREAD

**Issue by poes** [Swind/pure-python-adb#59]
```> devices = adb.devices()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ppadb\command\host\__init__.py", line 23, in devices
>     result = self._execute_cmd(cmd)
>   File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ppadb\command\host\__init__.py", line 14, in _execute_cmd
>     conn.send(cmd)
>   File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ppadb\connection.py", line 77, in send
>     return self._check_status()
>   File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ppadb\connection.py", line 83, in _check_status
>     raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
> RuntimeError: ERROR: 'Andr' oid Console: type 'help' for a list of commands
> OK
```

I have an android emulator running on port 5554.
You can see the device returns `OK` but ppadb still returns an error.

**Comment by Swind** [comment]
Hi @poes 
Could you provide more detail about this issue. 
e.g. your testing code, adb version and the android version of the emulator.
Thanks

**Comment by poes** [comment]
> Hi @poes 
> 
> Could you provide more detail about this issue. 
> 
> e.g. your testing code, adb version and the android version of the emulator.
> 
> Thanks

Thank you for responding @Swind 
I am using the newest version of android studio with the Nexus 5X I believe. The code is simply calling adb.devices().
Not at my PC right now. Will update this with more details in a few hours.
